import { type QueryRunner } from 'typeorm';

import { RegisteredInstanceCommand } from 'src/engine/core-modules/upgrade/decorators/registered-instance-command.decorator';
import { type FastInstanceCommand } from 'src/engine/core-modules/upgrade/interfaces/fast-instance-command.interface';

@RegisteredInstanceCommand('2.32.0', 1788982508902)
export class CreateInconnectMessagingTransportSpineFastInstanceCommand implements FastInstanceCommand {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE TABLE "core"."inconnectMessagingConfiguration" ("workspaceId" uuid NOT NULL, "anchorObjectMetadataId" uuid NOT NULL, "revision" bigint NOT NULL DEFAULT \'0\', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_INCONNECT_MSG_CONFIG_REVISION" CHECK ("revision" >= 0), CONSTRAINT "PK_INCONNECT_MSG_CONFIG" PRIMARY KEY ("workspaceId"))');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_CONFIG_WORKSPACE_ANCHOR_UNIQUE" ON "core"."inconnectMessagingConfiguration" ("workspaceId", "anchorObjectMetadataId") ');
    await queryRunner.query('CREATE TABLE "core"."inconnectMessagingProviderConnection" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspaceId" uuid NOT NULL, "provider" character varying NOT NULL, "channel" character varying NOT NULL, "displayName" text NOT NULL, "externalAccountIdentifier" text, "normalizedSenderAddress" text NOT NULL, "providerSenderOrServiceIdentifier" text, "inboundRoutingKey" text NOT NULL, "encryptedCredentials" text, "credentialsVersion" integer, "lifecycleStatus" character varying NOT NULL DEFAULT \'ENABLED\', "healthStatus" character varying NOT NULL DEFAULT \'UNKNOWN\', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_INCONNECT_MSG_CONNECTION_ROUTING_KEY" CHECK (btrim("inboundRoutingKey") <> \'\'), CONSTRAINT "CHK_INCONNECT_MSG_CONNECTION_CHANNEL" CHECK (btrim("channel") <> \'\'), CONSTRAINT "CHK_INCONNECT_MSG_CONNECTION_PROVIDER" CHECK (btrim("provider") <> \'\'), CONSTRAINT "CHK_INCONNECT_MSG_CONNECTION_CREDENTIALS" CHECK (("encryptedCredentials" IS NULL AND "credentialsVersion" IS NULL) OR ("encryptedCredentials" LIKE \'enc:v2:%\' AND "credentialsVersion" >= 1)), CONSTRAINT "CHK_INCONNECT_MSG_CONNECTION_HEALTH" CHECK ("healthStatus" IN (\'UNKNOWN\', \'HEALTHY\', \'DEGRADED\', \'UNHEALTHY\')), CONSTRAINT "CHK_INCONNECT_MSG_CONNECTION_LIFECYCLE" CHECK ("lifecycleStatus" IN (\'ENABLED\', \'DISABLED\')), CONSTRAINT "PK_INCONNECT_MSG_CONNECTION" PRIMARY KEY ("id"))');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_CONNECTION_WORKSPACE" ON "core"."inconnectMessagingProviderConnection" ("workspaceId") ');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_CONNECTION_ROUTING_UNIQUE" ON "core"."inconnectMessagingProviderConnection" ("provider", "channel", "inboundRoutingKey") ');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_CONNECTION_ID_WORKSPACE_UNIQUE" ON "core"."inconnectMessagingProviderConnection" ("id", "workspaceId") ');
    await queryRunner.query('CREATE TABLE "core"."inconnectMessagingConversation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspaceId" uuid NOT NULL, "providerConnectionId" uuid NOT NULL, "externalAddressNormalized" text NOT NULL, "waId" text, "linkedRecordObjectMetadataId" uuid, "linkedRecordId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_INCONNECT_MSG_CONVERSATION_ADDRESS" CHECK (btrim("externalAddressNormalized") <> \'\'), CONSTRAINT "CHK_INCONNECT_MSG_CONVERSATION_LINKED_TUPLE" CHECK (("linkedRecordObjectMetadataId" IS NULL AND "linkedRecordId" IS NULL) OR ("linkedRecordObjectMetadataId" IS NOT NULL AND "linkedRecordId" IS NOT NULL)), CONSTRAINT "PK_INCONNECT_MSG_CONVERSATION" PRIMARY KEY ("id"))');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_CONVERSATION_LINKED_RECORD" ON "core"."inconnectMessagingConversation" ("workspaceId", "linkedRecordObjectMetadataId", "linkedRecordId") WHERE "linkedRecordId" IS NOT NULL');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_CONVERSATION_CONNECTION" ON "core"."inconnectMessagingConversation" ("providerConnectionId") ');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_CONVERSATION_WORKSPACE" ON "core"."inconnectMessagingConversation" ("workspaceId") ');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_CONVERSATION_ID_CONNECTION_WORKSPACE_UNIQUE" ON "core"."inconnectMessagingConversation" ("id", "providerConnectionId", "workspaceId") ');
    await queryRunner.query('CREATE TABLE "core"."inconnectMessagingMessage" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspaceId" uuid NOT NULL, "conversationId" uuid NOT NULL, "providerConnectionId" uuid NOT NULL, "direction" character varying NOT NULL, "type" character varying NOT NULL, "sendMode" character varying, "body" text NOT NULL, "outboundState" character varying, "providerMessageId" text, "providerStatus" text, "clientRequestId" uuid, "requestFingerprint" text, "retryOfMessageId" uuid, "sentAt" TIMESTAMP WITH TIME ZONE, "deliveredAt" TIMESTAMP WITH TIME ZONE, "readAt" TIMESTAMP WITH TIME ZONE, "failedAt" TIMESTAMP WITH TIME ZONE, "error" jsonb, "providerMetadata" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_INCONNECT_MSG_MESSAGE_RETRY" CHECK ("retryOfMessageId" IS NULL OR ("direction" = \'OUTBOUND\' AND "retryOfMessageId" <> "id")), CONSTRAINT "CHK_INCONNECT_MSG_MESSAGE_DIRECTION_STATE" CHECK (("direction" = \'INBOUND\' AND "outboundState" IS NULL AND "sendMode" IS NULL) OR ("direction" = \'OUTBOUND\' AND "outboundState" IS NOT NULL AND "sendMode" IS NOT NULL)), CONSTRAINT "CHK_INCONNECT_MSG_MESSAGE_OUTBOUND_STATE" CHECK ("outboundState" IS NULL OR "outboundState" IN (\'QUEUED\', \'SENDING\', \'SENT\', \'DELIVERED\', \'READ\', \'FAILED\', \'UNKNOWN\')), CONSTRAINT "CHK_INCONNECT_MSG_MESSAGE_SEND_MODE" CHECK ("sendMode" IS NULL OR "sendMode" = \'FREEFORM\'), CONSTRAINT "CHK_INCONNECT_MSG_MESSAGE_TYPE" CHECK ("type" = \'TEXT\'), CONSTRAINT "CHK_INCONNECT_MSG_MESSAGE_DIRECTION" CHECK ("direction" IN (\'INBOUND\', \'OUTBOUND\')), CONSTRAINT "PK_INCONNECT_MSG_MESSAGE" PRIMARY KEY ("id"))');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_MESSAGE_CONVERSATION_CREATED" ON "core"."inconnectMessagingMessage" ("conversationId", "createdAt") ');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_MESSAGE_CLIENT_REQUEST_UNIQUE" ON "core"."inconnectMessagingMessage" ("workspaceId", "clientRequestId") WHERE "direction" = \'OUTBOUND\' AND "clientRequestId" IS NOT NULL');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_MESSAGE_PROVIDER_ID_UNIQUE" ON "core"."inconnectMessagingMessage" ("providerConnectionId", "providerMessageId") WHERE "providerMessageId" IS NOT NULL');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_MESSAGE_ID_CONNECTION_WORKSPACE_UNIQUE" ON "core"."inconnectMessagingMessage" ("id", "providerConnectionId", "workspaceId") ');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_MESSAGE_ID_WORKSPACE_UNIQUE" ON "core"."inconnectMessagingMessage" ("id", "workspaceId") ');
    await queryRunner.query('CREATE TABLE "core"."inconnectMessagingDispatchAttempt" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspaceId" uuid NOT NULL, "messageId" uuid NOT NULL, "attemptNumber" integer NOT NULL, "leaseToken" uuid, "leaseExpiresAt" TIMESTAMP WITH TIME ZONE, "startedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "providerRequestStartedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "outcome" character varying, "error" jsonb, "providerMetadata" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_INCONNECT_MSG_ATTEMPT_LEASE" CHECK (("leaseToken" IS NULL) = ("leaseExpiresAt" IS NULL)), CONSTRAINT "CHK_INCONNECT_MSG_ATTEMPT_OUTCOME" CHECK ("outcome" IS NULL OR "outcome" IN (\'ACCEPTED\', \'REJECTED_DEFINITIVE\', \'FAILED_BEFORE_SUBMIT\', \'UNKNOWN\')), CONSTRAINT "CHK_INCONNECT_MSG_ATTEMPT_NUMBER" CHECK ("attemptNumber" > 0), CONSTRAINT "PK_INCONNECT_MSG_ATTEMPT" PRIMARY KEY ("id"))');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_ATTEMPT_WORKSPACE" ON "core"."inconnectMessagingDispatchAttempt" ("workspaceId") ');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_ATTEMPT_MESSAGE_NUMBER_UNIQUE" ON "core"."inconnectMessagingDispatchAttempt" ("messageId", "attemptNumber") ');
    await queryRunner.query('CREATE TABLE "core"."inconnectMessagingOutboxEvent" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspaceId" uuid NOT NULL, "aggregateType" character varying NOT NULL, "aggregateId" uuid NOT NULL, "eventType" character varying NOT NULL, "immutablePayload" jsonb NOT NULL, "deduplicationKey" text NOT NULL, "availableAt" TIMESTAMP WITH TIME ZONE NOT NULL, "processingState" character varying NOT NULL DEFAULT \'PENDING\', "leaseToken" uuid, "leaseExpiresAt" TIMESTAMP WITH TIME ZONE, "attemptCount" integer NOT NULL DEFAULT \'0\', "error" jsonb, "publishedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_INCONNECT_MSG_OUTBOX_LEASE" CHECK (("leaseToken" IS NULL) = ("leaseExpiresAt" IS NULL)), CONSTRAINT "CHK_INCONNECT_MSG_OUTBOX_ATTEMPTS" CHECK ("attemptCount" >= 0), CONSTRAINT "CHK_INCONNECT_MSG_OUTBOX_STATE" CHECK ("processingState" IN (\'PENDING\', \'PROCESSING\', \'PUBLISHED\', \'FAILED\')), CONSTRAINT "PK_INCONNECT_MSG_OUTBOX" PRIMARY KEY ("id"))');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_OUTBOX_AGGREGATE" ON "core"."inconnectMessagingOutboxEvent" ("workspaceId", "aggregateType", "aggregateId") ');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_OUTBOX_AVAILABLE" ON "core"."inconnectMessagingOutboxEvent" ("processingState", "availableAt") ');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_OUTBOX_DEDUPLICATION_UNIQUE" ON "core"."inconnectMessagingOutboxEvent" ("deduplicationKey") ');
    await queryRunner.query('CREATE TABLE "core"."inconnectMessagingWebhookReceipt" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspaceId" uuid NOT NULL, "providerConnectionId" uuid NOT NULL, "eventKind" character varying NOT NULL, "idempotencyKey" text NOT NULL, "payloadHash" character varying(64) NOT NULL, "firstReceivedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "normalizedMetadata" jsonb, "processingState" character varying NOT NULL DEFAULT \'RECEIVED\', "leaseToken" uuid, "leaseExpiresAt" TIMESTAMP WITH TIME ZONE, "attemptCount" integer NOT NULL DEFAULT \'0\', "error" jsonb, "processedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_INCONNECT_MSG_WEBHOOK_LEASE" CHECK (("leaseToken" IS NULL) = ("leaseExpiresAt" IS NULL)), CONSTRAINT "CHK_INCONNECT_MSG_WEBHOOK_ATTEMPTS" CHECK ("attemptCount" >= 0), CONSTRAINT "CHK_INCONNECT_MSG_WEBHOOK_STATE" CHECK ("processingState" IN (\'RECEIVED\', \'PROCESSING\', \'PROCESSED\', \'FAILED\')), CONSTRAINT "PK_INCONNECT_MSG_WEBHOOK" PRIMARY KEY ("id"))');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_WEBHOOK_PROCESSING" ON "core"."inconnectMessagingWebhookReceipt" ("processingState", "firstReceivedAt") ');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_WEBHOOK_IDEMPOTENCY_UNIQUE" ON "core"."inconnectMessagingWebhookReceipt" ("providerConnectionId", "eventKind", "idempotencyKey") ');
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_INCONNECT_MSG_WEBHOOK_ID_WORKSPACE_UNIQUE" ON "core"."inconnectMessagingWebhookReceipt" ("id", "workspaceId") ');
    await queryRunner.query('CREATE TABLE "core"."inconnectMessagingProviderStatusEvent" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspaceId" uuid NOT NULL, "messageId" uuid NOT NULL, "webhookReceiptId" uuid, "providerEventKey" text, "originalStatus" text NOT NULL, "normalizedStatus" character varying NOT NULL, "providerOccurredAt" TIMESTAMP WITH TIME ZONE, "serverReceivedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "error" jsonb, "appliedToProjection" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_INCONNECT_MSG_STATUS_NORMALIZED" CHECK ("normalizedStatus" IN (\'QUEUED\', \'SENDING\', \'SENT\', \'DELIVERED\', \'READ\', \'FAILED\', \'UNKNOWN\')), CONSTRAINT "PK_INCONNECT_MSG_STATUS" PRIMARY KEY ("id"))');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_STATUS_RECEIPT" ON "core"."inconnectMessagingProviderStatusEvent" ("webhookReceiptId") ');
    await queryRunner.query('CREATE INDEX "IDX_INCONNECT_MSG_STATUS_MESSAGE_RECEIVED" ON "core"."inconnectMessagingProviderStatusEvent" ("messageId", "serverReceivedAt") ');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingConfiguration" ADD CONSTRAINT "FK_INCONNECT_MSG_CONFIG_WORKSPACE" FOREIGN KEY ("workspaceId") REFERENCES "core"."workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingConfiguration" ADD CONSTRAINT "FK_INCONNECT_MSG_CONFIG_ANCHOR" FOREIGN KEY ("anchorObjectMetadataId", "workspaceId") REFERENCES "core"."objectMetadata"("id","workspaceId") ON DELETE RESTRICT ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingProviderConnection" ADD CONSTRAINT "FK_INCONNECT_MSG_CONNECTION_WORKSPACE" FOREIGN KEY ("workspaceId") REFERENCES "core"."workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingConversation" ADD CONSTRAINT "FK_INCONNECT_MSG_CONVERSATION_WORKSPACE" FOREIGN KEY ("workspaceId") REFERENCES "core"."workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingConversation" ADD CONSTRAINT "FK_INCONNECT_MSG_CONVERSATION_CONNECTION" FOREIGN KEY ("providerConnectionId", "workspaceId") REFERENCES "core"."inconnectMessagingProviderConnection"("id","workspaceId") ON DELETE RESTRICT ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingConversation" ADD CONSTRAINT "FK_INCONNECT_MSG_CONVERSATION_ANCHOR" FOREIGN KEY ("workspaceId", "linkedRecordObjectMetadataId") REFERENCES "core"."inconnectMessagingConfiguration"("workspaceId","anchorObjectMetadataId") ON DELETE RESTRICT ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingMessage" ADD CONSTRAINT "FK_INCONNECT_MSG_MESSAGE_WORKSPACE" FOREIGN KEY ("workspaceId") REFERENCES "core"."workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingMessage" ADD CONSTRAINT "FK_INCONNECT_MSG_MESSAGE_CONVERSATION" FOREIGN KEY ("conversationId", "providerConnectionId", "workspaceId") REFERENCES "core"."inconnectMessagingConversation"("id","providerConnectionId","workspaceId") ON DELETE RESTRICT ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingMessage" ADD CONSTRAINT "FK_INCONNECT_MSG_MESSAGE_RETRY_OF" FOREIGN KEY ("retryOfMessageId", "providerConnectionId", "workspaceId") REFERENCES "core"."inconnectMessagingMessage"("id","providerConnectionId","workspaceId") ON DELETE RESTRICT ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingDispatchAttempt" ADD CONSTRAINT "FK_INCONNECT_MSG_ATTEMPT_WORKSPACE" FOREIGN KEY ("workspaceId") REFERENCES "core"."workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingDispatchAttempt" ADD CONSTRAINT "FK_INCONNECT_MSG_ATTEMPT_MESSAGE" FOREIGN KEY ("messageId", "workspaceId") REFERENCES "core"."inconnectMessagingMessage"("id","workspaceId") ON DELETE CASCADE ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingOutboxEvent" ADD CONSTRAINT "FK_INCONNECT_MSG_OUTBOX_WORKSPACE" FOREIGN KEY ("workspaceId") REFERENCES "core"."workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingWebhookReceipt" ADD CONSTRAINT "FK_INCONNECT_MSG_WEBHOOK_WORKSPACE" FOREIGN KEY ("workspaceId") REFERENCES "core"."workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingWebhookReceipt" ADD CONSTRAINT "FK_INCONNECT_MSG_WEBHOOK_CONNECTION" FOREIGN KEY ("providerConnectionId", "workspaceId") REFERENCES "core"."inconnectMessagingProviderConnection"("id","workspaceId") ON DELETE RESTRICT ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingProviderStatusEvent" ADD CONSTRAINT "FK_INCONNECT_MSG_STATUS_WORKSPACE" FOREIGN KEY ("workspaceId") REFERENCES "core"."workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingProviderStatusEvent" ADD CONSTRAINT "FK_INCONNECT_MSG_STATUS_MESSAGE" FOREIGN KEY ("messageId", "workspaceId") REFERENCES "core"."inconnectMessagingMessage"("id","workspaceId") ON DELETE CASCADE ON UPDATE NO ACTION');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingProviderStatusEvent" ADD CONSTRAINT "FK_INCONNECT_MSG_STATUS_RECEIPT" FOREIGN KEY ("webhookReceiptId", "workspaceId") REFERENCES "core"."inconnectMessagingWebhookReceipt"("id","workspaceId") ON DELETE RESTRICT ON UPDATE NO ACTION');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingProviderStatusEvent" DROP CONSTRAINT "FK_INCONNECT_MSG_STATUS_RECEIPT"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingProviderStatusEvent" DROP CONSTRAINT "FK_INCONNECT_MSG_STATUS_MESSAGE"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingProviderStatusEvent" DROP CONSTRAINT "FK_INCONNECT_MSG_STATUS_WORKSPACE"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingWebhookReceipt" DROP CONSTRAINT "FK_INCONNECT_MSG_WEBHOOK_CONNECTION"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingWebhookReceipt" DROP CONSTRAINT "FK_INCONNECT_MSG_WEBHOOK_WORKSPACE"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingOutboxEvent" DROP CONSTRAINT "FK_INCONNECT_MSG_OUTBOX_WORKSPACE"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingDispatchAttempt" DROP CONSTRAINT "FK_INCONNECT_MSG_ATTEMPT_MESSAGE"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingDispatchAttempt" DROP CONSTRAINT "FK_INCONNECT_MSG_ATTEMPT_WORKSPACE"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingMessage" DROP CONSTRAINT "FK_INCONNECT_MSG_MESSAGE_RETRY_OF"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingMessage" DROP CONSTRAINT "FK_INCONNECT_MSG_MESSAGE_CONVERSATION"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingMessage" DROP CONSTRAINT "FK_INCONNECT_MSG_MESSAGE_WORKSPACE"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingConversation" DROP CONSTRAINT "FK_INCONNECT_MSG_CONVERSATION_ANCHOR"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingConversation" DROP CONSTRAINT "FK_INCONNECT_MSG_CONVERSATION_CONNECTION"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingConversation" DROP CONSTRAINT "FK_INCONNECT_MSG_CONVERSATION_WORKSPACE"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingProviderConnection" DROP CONSTRAINT "FK_INCONNECT_MSG_CONNECTION_WORKSPACE"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingConfiguration" DROP CONSTRAINT "FK_INCONNECT_MSG_CONFIG_ANCHOR"');
    await queryRunner.query('ALTER TABLE "core"."inconnectMessagingConfiguration" DROP CONSTRAINT "FK_INCONNECT_MSG_CONFIG_WORKSPACE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_STATUS_MESSAGE_RECEIVED"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_STATUS_RECEIPT"');
    await queryRunner.query('DROP TABLE "core"."inconnectMessagingProviderStatusEvent"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_WEBHOOK_ID_WORKSPACE_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_WEBHOOK_IDEMPOTENCY_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_WEBHOOK_PROCESSING"');
    await queryRunner.query('DROP TABLE "core"."inconnectMessagingWebhookReceipt"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_OUTBOX_DEDUPLICATION_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_OUTBOX_AVAILABLE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_OUTBOX_AGGREGATE"');
    await queryRunner.query('DROP TABLE "core"."inconnectMessagingOutboxEvent"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_ATTEMPT_MESSAGE_NUMBER_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_ATTEMPT_WORKSPACE"');
    await queryRunner.query('DROP TABLE "core"."inconnectMessagingDispatchAttempt"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_MESSAGE_ID_WORKSPACE_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_MESSAGE_ID_CONNECTION_WORKSPACE_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_MESSAGE_PROVIDER_ID_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_MESSAGE_CLIENT_REQUEST_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_MESSAGE_CONVERSATION_CREATED"');
    await queryRunner.query('DROP TABLE "core"."inconnectMessagingMessage"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_CONVERSATION_ID_CONNECTION_WORKSPACE_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_CONVERSATION_WORKSPACE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_CONVERSATION_CONNECTION"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_CONVERSATION_LINKED_RECORD"');
    await queryRunner.query('DROP TABLE "core"."inconnectMessagingConversation"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_CONNECTION_ID_WORKSPACE_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_CONNECTION_ROUTING_UNIQUE"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_CONNECTION_WORKSPACE"');
    await queryRunner.query('DROP TABLE "core"."inconnectMessagingProviderConnection"');
    await queryRunner.query('DROP INDEX "core"."IDX_INCONNECT_MSG_CONFIG_WORKSPACE_ANCHOR_UNIQUE"');
    await queryRunner.query('DROP TABLE "core"."inconnectMessagingConfiguration"');
  }
}
